# Documentation: https://github.com/compose-spec/compose-spec/blob/master/spec.md
# Purpose: Build local containers for the Mutillidae environment

version: '3.7'
services:

  database:
    image: webpwnized/mutillidae:database
    build: 
        context: ./database
        dockerfile: Dockerfile
    ports:
      - 3306:3306
      - 33060:33060
    networks:
      - datanet   

  database_admin:
    depends_on:
      - database
    image: webpwnized/mutillidae:database_admin
    build:
        context: ./database_admin
        dockerfile: Dockerfile
    ports:
      - 81:80
    networks:
      - datanet   

  www:
    depends_on:
      - database
      - directory
    image: webpwnized/mutillidae:www
    build:
        context: ./www
        dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    networks:
      - datanet
      - ldapnet

  directory:
    image: webpwnized/mutillidae:ldap
    build:
        context: ./ldap
        dockerfile: Dockerfile
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    ports:
      - 389:389
      - 636:636
    networks:
      - ldapnet

  directory_admin:
    depends_on:
      - directory
    image: webpwnized/mutillidae:ldap_admin
    build:
        context: ./ldap_admin          
        dockerfile: Dockerfile
    ports:
      - 82:80
    networks:
      - ldapnet

volumes:
  ldap_data:
  ldap_config:

# Create network segments for the containers to use
networks:
    datanet:
    ldapnet:
